# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homme.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1356, 751)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1070, 508, 251, 81))
        self.pushButton_5.setStyleSheet("background-color: transparent;\n"
"\n"
"color: rgb(170, 255, 255);\n"
"font: 20pt \"Segoe Print\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1050, 490, 281, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1050, 370, 281, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(1070, 388, 251, 81))
        self.pushButton_6.setStyleSheet("background-color: transparent;\n"
"\n"
"color: rgb(170, 255, 255);\n"
"font: 18pt \"Segoe Print\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1050, 250, 281, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(1070, 268, 251, 81))
        self.pushButton_7.setStyleSheet("background-color: transparent;\n"
"\n"
"color: rgb(170, 255, 255);\n"
"font: 16pt \"Segoe Print\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1050, 130, 281, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(1070, 148, 251, 81))
        self.pushButton_8.setStyleSheet("background-color: transparent;\n"
"\n"
"color: rgb(170, 255, 255);\n"
"font: 20pt \"Segoe Print\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1050, 10, 281, 111))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(1070, 30, 251, 81))
        self.pushButton_10.setStyleSheet("background-color: transparent;\n"
"\n"
"color: rgb(170, 255, 255);\n"
"font: 20pt \"Segoe Print\";")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(210, -140, 701, 371))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\OGC.gif"))
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 0, 101, 91))
        self.label_8.setStyleSheet("font: 75 26pt \"Segoe Print\";\n"
"color: rgb(170, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 620, 991, 61))
        self.lineEdit.setStyleSheet("font: 75 22pt \"Segoe Print\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(132, 0, 198);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(35, 615, 1001, 71))
        self.label_9.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(110, 110, 701, 461))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\9116f7fd184238ada99fdff9e2f2e3ac.gif"))
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(920, 45, 121, 41))
        self.comboBox.setStyleSheet("color: rgb(170, 255, 255);\n"
"font: 20pt \"Segoe Print\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2.raise_()
        self.pushButton_5.raise_()
        self.label_3.raise_()
        self.pushButton_6.raise_()
        self.label_4.raise_()
        self.pushButton_7.raise_()
        self.label_5.raise_()
        self.pushButton_8.raise_()
        self.label_6.raise_()
        self.pushButton_10.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.lineEdit.raise_()
        self.label_10.raise_()
        self.comboBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1356, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_5.setText(_translate("MainWindow", "Exit"))
        self.pushButton_6.setText(_translate("MainWindow", "Image Generator"))
        self.pushButton_7.setText(_translate("MainWindow", "Webpage Generator"))
        self.pushButton_8.setText(_translate("MainWindow", "PPT Generator"))
        self.pushButton_10.setText(_translate("MainWindow", "Smart Home"))
        self.label_8.setText(_translate("MainWindow", "Luna"))
        self.comboBox.setItemText(0, _translate("MainWindow", "voice 1 "))
        self.comboBox.setItemText(1, _translate("MainWindow", "voice 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "voice 3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "voice 4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "voice 5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "voice 6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "voice 7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "voice 8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
