# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smarthome.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_smart(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1356, 737)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 601, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\digitalloop.gif"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(610, 230, 311, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1040, 230, 311, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1040, 490, 311, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 490, 311, 141))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 0, 251, 131))
        self.label_6.setStyleSheet("color: rgb(170, 255, 255);\n"
"font: 75 28pt \"Segoe Print\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(890, 120, 171, 131))
        self.label_7.setStyleSheet("color: rgb(170, 255, 255);\n"
"font: 75 28pt \"Segoe Print\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(890, 380, 171, 131))
        self.label_8.setStyleSheet("color: rgb(170, 255, 255);\n"
"font: 75 28pt \"Segoe Print\";")
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 250, 281, 101))
        self.pushButton.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"font: 75 20pt \"Segoe Print\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 510, 281, 101))
        self.pushButton_2.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"font: 75 20pt \"Segoe Print\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1050, 250, 281, 101))
        self.pushButton_3.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"font: 75 20pt \"Segoe Print\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1060, 510, 281, 101))
        self.pushButton_4.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"font: 75 20pt \"Segoe Print\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(100, 570, 311, 141))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:\\Users\\sujay\\Desktop\\python\\sujay\\Resources\\button 3.PNG"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 590, 281, 101))
        self.pushButton_5.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"font: 75 20pt \"Segoe Print\";")
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1356, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Smart Home"))
        self.label_7.setText(_translate("MainWindow", "Device 1"))
        self.label_8.setText(_translate("MainWindow", "Device 2"))
        self.pushButton.setText(_translate("MainWindow", "ON"))
        self.pushButton_2.setText(_translate("MainWindow", "ON"))
        self.pushButton_3.setText(_translate("MainWindow", "OFF"))
        self.pushButton_4.setText(_translate("MainWindow", "OFF"))
        self.pushButton_5.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_smart()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
